#!/usr/bin/env bash
# ============================================================================
#  Static (compile-time) verification of the Arduino firmware
# ============================================================================
#
#  The Arduino UNO R4 toolchain is not required and is NOT used here. This
#  script compiles `environmental_monitor.ino` with a normal C++ compiler
#  against the API stubs in ./stubs, in both supported sensor configurations.
#
#  It proves:
#    * the sketch is syntactically valid C++ and uses the documented APIs
#      with the right names, arities and types
#    * the pin-map static_asserts pass (no two signals share a pin)
#    * it compiles clean under -Wall -Wextra -Werror
#
#  It does NOT prove the firmware runs on hardware - no sensor is read, no pin
#  is driven, nothing is uploaded. See arduino/README.md.
#
#  Usage:  bash arduino/static_check/run.sh
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKETCH_DIR="$(cd "$HERE/../environmental_monitor" && pwd)"

STD="-std=c++17"
WARNINGS="-Wall -Wextra -Werror -Wno-unused-parameter"

# Pick a compiler that actually ships a C++ standard library. clang++ without
# libstdc++/libc++ installed cannot find <cmath>, so each candidate is probed
# with a real C++ translation unit rather than just looked up on PATH.
probe_compiler() {
  local candidate="$1"
  command -v "$candidate" >/dev/null 2>&1 || return 1
  printf '#include <cmath>\n#include <map>\n#include <string>\nint main(){return 0;}\n' > "$TMP_PROBE/main.cpp"
  for std in "-std=c++17" "-std=c++14" "-std=c++11"; do
    if "$candidate" "$std" -fsyntax-only "$TMP_PROBE/main.cpp" >/dev/null 2>&1; then
      STD="$std"
      return 0
    fi
  done
  return 1
}

TMP_PROBE="$(mktemp -d 2>/dev/null || mktemp -d -t envmon-probe)"
trap 'rm -rf "$TMP_PROBE"' EXIT

CXX_BIN="${CXX:-}"
if [ -n "$CXX_BIN" ]; then
  probe_compiler "$CXX_BIN" || { echo "FAIL: \$CXX=$CXX_BIN cannot compile C++." >&2; exit 2; }
else
  CXX_BIN=""
  for candidate in g++ clang++ c++ g++-14 g++-13 g++-12; do
    if probe_compiler "$candidate"; then CXX_BIN="$candidate"; break; fi
  done
fi
if [ -z "$CXX_BIN" ]; then
  echo "FAIL: no usable C++ compiler with a standard library found." >&2
  exit 2
fi
echo "Compiler: $CXX_BIN $STD"
echo

FAILED=0

run_pass() {
  local label="$1"
  shift
  echo "== $label"
  if "$CXX_BIN" $STD $WARNINGS -I "$HERE/stubs" -fsyntax-only "$@" "$HERE/host_check.cpp"; then
    echo "   PASS"
  else
    echo "   FAIL"
    FAILED=1
  fi
}

# --- pass 1: the default configuration (AM2302 / DHT22 on D2, one-wire) -----
run_pass "AM2302/DHT22 build (default config.example.h)"

# --- pass 2: the DHT12 configuration (I2C 0x5C) -----------------------------
# A throwaway copy of the sketch with a generated config.h, so the checked-in
# files are never touched and the user's real config.h is never shadowed.
TMP_DIR="$(mktemp -d 2>/dev/null || mktemp -d -t envmon)"
trap 'rm -rf "$TMP_DIR"' EXIT

cp "$SKETCH_DIR/environmental_monitor.ino" "$TMP_DIR/"
cat > "$TMP_DIR/config.h" <<'CONFIG'
/* Generated by arduino/static_check/run.sh - not part of the project. */
#ifndef ENVMON_CONFIG_H
#define ENVMON_CONFIG_H
#define WIFI_SSID "CHECK"
#define WIFI_PASSWORD "CHECK"
#define BACKEND_HOST "192.168.1.50"
#define BACKEND_PORT 8000
#define BACKEND_PATH "/api/v1/sensors/data"
#define RISK_STATE_PATH "/api/v1/device/%s/risk-state"
#define API_KEY "CHECK"
#define DEVICE_ID "arduino-r4-wifi-01"
#define FIRMWARE_VERSION "1.0.0"
#define SEND_INTERVAL_MS 15000UL
#define RISK_POLL_INTERVAL_MS 15000UL
#define WIFI_RETRY_INTERVAL_MS 5000UL
#define WIFI_ASSOC_TIMEOUT_MS 20000UL
#define HTTP_TIMEOUT_MS 6000UL
#define SERIAL_BAUD 115200
#define SENSOR_AM2302_DHT22 1
#define SENSOR_DHT12_I2C 2
#define TEMP_HUMIDITY_SENSOR SENSOR_DHT12_I2C
#define PIN_DHT 2
#define DHT_TYPE DHT22
#define DHT12_I2C_ADDRESS 0x5C
#define PIN_RAIN_ANALOG A0
#define PIN_LDR_ANALOG A1
#define PIN_MQ135_ANALOG A2
#define BMP280_I2C_ADDRESS 0x76
#define PIN_LED_1 3
#define PIN_LED_2 4
#define PIN_LED_3 5
#define PIN_LED_4 6
#define PIN_LED_5 7
#define LED_ACTIVE_HIGH 1
#define PIN_BUZZER 8
#define BUZZER_PASSIVE 1
#define BUZZER_FREQUENCY_HZ 2300
#define ADC_MAX 1023
#define RAIN_DRY_ADC 950
#define RAIN_WET_ADC 250
#define LIGHT_DARK_ADC 40
#define LIGHT_BRIGHT_ADC 900
#define AIR_QUALITY_CLEAN_ADC 180
#define TEMP_MIN_C -40.0F
#define TEMP_MAX_C 85.0F
#define HUMIDITY_MIN_PCT 0.0F
#define HUMIDITY_MAX_PCT 100.0F
#define PRESSURE_MIN_HPA 300.0F
#define PRESSURE_MAX_HPA 1100.0F
#define SENSOR_FAILURE_LIMIT 3
#endif
CONFIG

cat > "$TMP_DIR/host_check.cpp" <<'DRIVER'
#include "stubs.hpp"
HostSerial Serial;
HostWiFi WiFi;
HostWire Wire;
#include "environmental_monitor.ino"
int main() {
  setup();
  return 0;
}
DRIVER

echo "== DHT12 over I2C build (generated config.h)"
if "$CXX_BIN" $STD $WARNINGS -I "$HERE/stubs" -I "$TMP_DIR" -fsyntax-only "$TMP_DIR/host_check.cpp"; then
  echo "   PASS"
else
  echo "   FAIL"
  FAILED=1
fi

# --- pass 3: the invalid combination must be rejected at compile time -------
# If someone selects a sensor the firmware does not implement, the build must
# fail loudly rather than silently produce wrong readings.
cat > "$TMP_DIR/config.h" <<'CONFIG'
#ifndef ENVMON_CONFIG_H
#define ENVMON_CONFIG_H
#define SENSOR_AM2302_DHT22 1
#define SENSOR_DHT12_I2C 2
#define TEMP_HUMIDITY_SENSOR 99
#define PIN_RAIN_ANALOG A0
#define PIN_LDR_ANALOG A1
#define PIN_MQ135_ANALOG A2
#define PIN_LED_1 3
#define PIN_LED_2 4
#define PIN_LED_3 5
#define PIN_LED_4 6
#define PIN_LED_5 7
#define PIN_BUZZER 8
#endif
CONFIG

echo "== unsupported sensor selection must fail the build"
NEGATIVE_LOG="$TMP_DIR/negative.log"
if "$CXX_BIN" $STD -I "$HERE/stubs" -I "$TMP_DIR" -fsyntax-only "$TMP_DIR/host_check.cpp" >"$NEGATIVE_LOG" 2>&1; then
  echo "   FAIL: an unsupported TEMP_HUMIDITY_SENSOR compiled without an error"
  FAILED=1
elif grep -q "TEMP_HUMIDITY_SENSOR must be" "$NEGATIVE_LOG"; then
  echo "   PASS (rejected by the intended #error)"
else
  echo "   FAIL: the build broke, but not for the intended reason:"
  sed 's/^/     /' "$NEGATIVE_LOG" | head -5
  FAILED=1
fi

# --- pass 4: a duplicated pin must fail the pin-map assertion --------------
cat > "$TMP_DIR/config.h" <<'CONFIG'
#ifndef ENVMON_CONFIG_H
#define ENVMON_CONFIG_H
#define SENSOR_AM2302_DHT22 1
#define SENSOR_DHT12_I2C 2
#define TEMP_HUMIDITY_SENSOR SENSOR_AM2302_DHT22
#define PIN_DHT 2
#define PIN_RAIN_ANALOG A0
#define PIN_LDR_ANALOG A1
#define PIN_MQ135_ANALOG A2
#define PIN_LED_1 3
#define PIN_LED_2 4
#define PIN_LED_3 5
#define PIN_LED_4 6
#define PIN_LED_5 7
#define PIN_BUZZER 7
#endif
CONFIG

echo "== a duplicated pin must fail the pin-map assertion"
if "$CXX_BIN" $STD -I "$HERE/stubs" -I "$TMP_DIR" -fsyntax-only "$TMP_DIR/host_check.cpp" >"$NEGATIVE_LOG" 2>&1; then
  echo "   FAIL: two signals on pin 7 compiled without an error"
  FAILED=1
elif grep -q "Pin conflict" "$NEGATIVE_LOG"; then
  echo "   PASS (rejected by the intended static_assert)"
else
  echo "   FAIL: the build broke, but not for the intended reason:"
  sed 's/^/     /' "$NEGATIVE_LOG" | head -5
  FAILED=1
fi

echo
if [ "$FAILED" -eq 0 ]; then
  echo "Static firmware checks: PASS (compile-time only - hardware untested)"
else
  echo "Static firmware checks: FAIL" >&2
fi
exit "$FAILED"
