"""Alembic migration validation.

The API used to create its schema with ``Base.metadata.create_all()`` only, which
means a clean checkout, an existing database and a future schema change had no
shared upgrade path. These tests pin the migration story down:

* ``alembic upgrade head`` builds a schema that matches the ORM metadata exactly
  (table by table, column by column) - so an autogenerated migration cannot drift
  away from the models
* the initial migration is a no-op against a database that was already built by
  ``create_all`` (an existing deployment is not destroyed or half-migrated)
* ``alembic downgrade base`` removes what it created, so the path is reversible
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest
from sqlalchemy import create_engine, inspect

BACKEND_DIR = Path(__file__).resolve().parents[1]


def _schema(url: str) -> dict[str, set[str]]:
    """Table name -> column names, for a real database file.

    The engine is disposed before returning: on Windows an open SQLite handle
    keeps the file locked, which would make the temporary directory un-removable
    and turn a passing test into a flaky PermissionError.
    """
    engine = create_engine(url)
    try:
        inspector = inspect(engine)
        return {
            table: {column["name"] for column in inspector.get_columns(table)}
            for table in inspector.get_table_names()
            if table != "alembic_version"
        }
    finally:
        engine.dispose()


def _run_alembic(*args: str, url: str) -> None:
    """Run alembic in-process against an explicit database URL.

    Uses ``ALEMBIC_DATABASE_URL`` (honoured by alembic/env.py) rather than
    mutating ``DATABASE_URL`` or clearing the settings cache: those are global to
    the process, and touching them leaked into other tests' fixtures.
    """
    import os

    from alembic import command
    from alembic.config import Config

    previous = os.environ.get("ALEMBIC_DATABASE_URL")
    os.environ["ALEMBIC_DATABASE_URL"] = url
    try:
        config = Config(str(BACKEND_DIR / "alembic.ini"))
        if args[0] == "upgrade":
            command.upgrade(config, "head")
        else:
            command.downgrade(config, args[1])
    finally:
        if previous is None:
            os.environ.pop("ALEMBIC_DATABASE_URL", None)
        else:
            os.environ["ALEMBIC_DATABASE_URL"] = previous


def test_migration_builds_the_same_schema_as_the_orm_metadata():
    """`alembic upgrade head` must produce exactly what create_all() produces."""
    from app.core.database import Base

    from app import models  # noqa: F401  (register the metadata)

    with tempfile.TemporaryDirectory(prefix="envmon-migrations-") as tmpdir:
        migrated_url = f"sqlite:///{Path(tmpdir, 'migrated.db').as_posix()}"
        _run_alembic("upgrade", "head", url=migrated_url)

        # The reference schema: what the ORM models describe.
        reference_url = f"sqlite:///{Path(tmpdir, 'reference.db').as_posix()}"
        reference_engine = create_engine(reference_url)
        try:
            Base.metadata.create_all(bind=reference_engine)
        finally:
            reference_engine.dispose()

        migrated = _schema(migrated_url)
        reference = _schema(reference_url)

        assert migrated.keys() == reference.keys(), "table set differs from the ORM"
        for table, columns in reference.items():
            assert migrated[table] == columns, (
                f"{table} columns differ: migration={sorted(migrated[table])} "
                f"orm={sorted(columns)}"
            )


def test_migration_is_a_noop_on_a_create_all_database():
    """An existing deployment (built by create_all) must not be destroyed."""
    from app.core.database import Base

    from app import models  # noqa: F401

    with tempfile.TemporaryDirectory(prefix="envmon-existing-") as tmpdir:
        url = f"sqlite:///{Path(tmpdir, 'existing.db').as_posix()}"
        engine = create_engine(url)
        try:
            Base.metadata.create_all(bind=engine)
        finally:
            engine.dispose()
        before = _schema(url)

        _run_alembic("upgrade", "head", url=url)

        assert _schema(url) == before, "the existing schema was altered"

        # ...and the revision is recorded, so later migrations apply on top.
        check_engine = create_engine(url)
        try:
            assert "alembic_version" in inspect(check_engine).get_table_names()
        finally:
            check_engine.dispose()


def test_migration_downgrade_removes_the_schema():
    with tempfile.TemporaryDirectory(prefix="envmon-downgrade-") as tmpdir:
        url = f"sqlite:///{Path(tmpdir, 'down.db').as_posix()}"
        _run_alembic("upgrade", "head", url=url)
        assert _schema(url), "upgrade created nothing"

        _run_alembic("downgrade", "base", url=url)
        assert _schema(url) == {}, "downgrade left tables behind"


def test_alembic_is_a_declared_dependency():
    """A migration strategy nobody can run is not a migration strategy."""
    requirements = (BACKEND_DIR / "requirements.txt").read_text(encoding="utf-8")
    assert "alembic" in requirements.lower()
