"""initial schema

Revision ID: 81abd09e8c98
Revises: 
Create Date: 2026-09-15 23:04:09.182468
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

#: The application's timezone-aware datetime column type. Imported here so the
#: migration is self-contained (it must not rely on the ORM models, which
#: change over time; migrations describe the schema as it was).
from app.core.database import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = '81abd09e8c98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    """True when the table already exists (created by ``create_all`` pre-Alembic)."""
    inspector = sa.inspect(op.get_bind())
    return name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A database that predates Alembic was built by Base.metadata.create_all().
    # Creating the tables again would abort half-way, so this migration honours
    # the existing schema and only records the revision (the shape is identical
    # because both come from the same ORM metadata). New databases take the
    # create_table path below.
    existing = {
        table
        for table in ("alerts", "chat_messages", "devices", "predictions", "sensor_readings")
        if _has_table(table)
    }
    if existing == {"alerts", "chat_messages", "devices", "predictions", "sensor_readings"}:
        return
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sensor', sa.String(length=40), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('triggered_at', UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', UTCDateTime(), nullable=False),
    sa.Column('resolved_at', UTCDateTime(), nullable=True),
    sa.Column('acknowledged_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('grounding', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('devices',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('uptime_ms', sa.Integer(), nullable=True),
    sa.Column('transmission_interval_ms', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sensors_available', sa.JSON(), nullable=True),
    sa.Column('sensors_missing', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('first_seen_at', UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', UTCDateTime(), nullable=False),
    sa.Column('last_payload_at', UTCDateTime(), nullable=True),
    sa.Column('total_readings', sa.Integer(), nullable=False),
    sa.Column('rejected_payloads', sa.Integer(), nullable=False),
    sa.Column('missed_intervals', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=True),
    sa.Column('last_risk_level', sa.Integer(), nullable=True),
    sa.Column('last_risk_score', sa.Float(), nullable=True),
    sa.Column('last_risk_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('target_at', UTCDateTime(), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('reasoning', sa.JSON(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('evaluated', sa.Boolean(), nullable=False),
    sa.Column('absolute_error', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_evaluated'), ['evaluated'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_target_at'), ['target_at'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('measured_at', UTCDateTime(), nullable=False),
    sa.Column('received_at', UTCDateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('bmp_temperature_c', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('rain_raw', sa.Float(), nullable=True),
    sa.Column('rain_pct', sa.Float(), nullable=True),
    sa.Column('ldr_raw', sa.Float(), nullable=True),
    sa.Column('light_pct', sa.Float(), nullable=True),
    sa.Column('air_quality_raw', sa.Float(), nullable=True),
    sa.Column('air_quality_index', sa.Float(), nullable=True),
    sa.Column('heat_index_c', sa.Float(), nullable=True),
    sa.Column('dew_point_c', sa.Float(), nullable=True),
    sa.Column('rain_status', sa.String(length=24), nullable=True),
    sa.Column('light_status', sa.String(length=24), nullable=True),
    sa.Column('air_quality_status', sa.String(length=24), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Integer(), nullable=True),
    sa.Column('risk_label', sa.String(length=24), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('risk_reasons', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('anomalies', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('uptime_ms', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('transmission_interval_ms', sa.Integer(), nullable=True),
    sa.Column('payload_bytes', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_reading_device_measured', ['device_id', 'measured_at'], unique=False)
        batch_op.create_index('ix_reading_device_received', ['device_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_measured_at'), ['measured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_risk_score'), ['risk_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_readings_risk_score'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_risk_level'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_received_at'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_measured_at'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_device_id'))
        batch_op.drop_index('ix_reading_device_received')
        batch_op.drop_index('ix_reading_device_measured')

    op.drop_table('sensor_readings')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_target_at'))
        batch_op.drop_index(batch_op.f('ix_predictions_metric'))
        batch_op.drop_index(batch_op.f('ix_predictions_evaluated'))
        batch_op.drop_index(batch_op.f('ix_predictions_device_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    op.drop_table('devices')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_active'))
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_alerts_device_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_category'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
